/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AlterarSenhasForm2.java
 *
 * Created on 22/11/2011, 13:21:34
 */
package br.com.controlcheque.client.telas;

import br.com.controlcheque.client.App;
import br.com.controlcheque.client.ServicesImpl.UsuarioServerImpl;
import br.com.controlcheque.client.util.ClientConstantes;
import br.com.controlcheque.service.Usuario;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Diego
 */
public class AlterarSenhasForm extends BaseForm {

    private Usuario usuario;

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    /**
     * Creates new form AlterarSenhasForm2
     */
    public AlterarSenhasForm() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        this.usuario = new Usuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        txt_novaSenha = new javax.swing.JPasswordField();
        txt_confirmaSenha = new javax.swing.JPasswordField();
        lbl_novaSenha = new javax.swing.JLabel();
        lbl_confirmaSenha = new javax.swing.JLabel();
        cb_usuario = new javax.swing.JComboBox();
        lbl_usuario = new javax.swing.JLabel();
        btn_alterar = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Altera Senhas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEtchedBorder()), "Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(43, 116, 185))); // NOI18N

        txt_confirmaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_confirmaSenhaActionPerformed(evt);
            }
        });

        lbl_novaSenha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl_novaSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_novaSenha.setText("Nova Senha");

        lbl_confirmaSenha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl_confirmaSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_confirmaSenha.setText("Confirmar Senha");

        cb_usuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADMINISTRADOR", "FUNCIONARIO" }));

        lbl_usuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_usuario.setText("Usuário");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_novaSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_novaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                        .addComponent(lbl_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_usuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_confirmaSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_confirmaSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(cb_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_novaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_novaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_confirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_confirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btn_alterar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/img_edit_32x32.png"))); // NOI18N
        btn_alterar.setText("Alterar");
        btn_alterar.setFocusPainted(false);
        btn_alterar.setFocusable(false);
        btn_alterar.setPreferredSize(new java.awt.Dimension(150, 40));
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_sair.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/sair32x32.png"))); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.setFocusPainted(false);
        btn_sair.setFocusable(false);
        btn_sair.setPreferredSize(new java.awt.Dimension(150, 40));
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_confirmaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_confirmaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_confirmaSenhaActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        // TODO add your handling code here:
        alterar();
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_btn_sairActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_sair;
    private javax.swing.JComboBox cb_usuario;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_confirmaSenha;
    private javax.swing.JLabel lbl_novaSenha;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JPasswordField txt_confirmaSenha;
    private javax.swing.JPasswordField txt_novaSenha;
    // End of variables declaration//GEN-END:variables

    /**
     * fecha o formulario
     */
    private void close() {
        this.dispose();
    }

    /**
     * Alterar Senha
     */
    private void alterar() {
        if (validateForm()) {
            pushToModel();
            mantemSenha();
        }
    }

    /**
     * mantemSenha
     *
     * @return
     */
    private void mantemSenha() {
        final JDialogProcessando aguarde = new JDialogProcessando(this, "Aguarde...", "Aguarde Processando...");
        aguarde.setVisible(true);
        SwingWorker<Usuario, Void> worker = new SwingWorker<Usuario, Void>() {

            @Override
            protected Usuario doInBackground() throws Exception {
                try {
                    setEnableBotoes(false);
                    return (Usuario) new UsuarioServerImpl().mantemObject(usuario);
                } catch (Exception ex) {
                    aguarde.setVisible(false);
                    throw ex;
                }

            }

            @Override
            protected void done() {
                aguarde.setVisible(false);
                try {
                    if (get() != null) {
                        Usuario result = (Usuario) get();
                        App.usuarioLogado = result;
                        JOptionPane.showMessageDialog(rootPane, "Senha alterada com sucesso.", "Sucesso", 1);
                        dispose();
                    }
                    setEnableBotoes(true);
                } catch (Exception ex) {
                    tratarErro(LoginForm.class, ex);
                }
            }
        };

        worker.execute();
    }

    /**
     * valida campos obrigatorios
     *
     * @return
     */
    private boolean validateForm() {

        String msgErro = "";

        if (txt_novaSenha.getText().trim().isEmpty()) {
            msgErro = "Campo nova senha em branco.";
            txt_novaSenha.setText("");
        }

        if (txt_confirmaSenha.getText().trim().isEmpty()) {
            if (!msgErro.isEmpty()) {
                msgErro += "\n";
            }

            msgErro += "Campo confirmar senha em branco.";
            txt_confirmaSenha.setText("");
        }

        if (!txt_novaSenha.getText().trim().isEmpty() && !txt_confirmaSenha.getText().trim().isEmpty()) {
            if (!txt_novaSenha.getText().equals(txt_confirmaSenha.getText())) {
                msgErro = "As senhas informadas são diferentes.";
            }
        }

        if (!msgErro.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, msgErro, "Atenção", 2);
            return false;
        }
        return true;
    }

    private void pushToModel() {
        this.usuario.setLogin(cb_usuario.getSelectedItem().toString());
        this.usuario.setSenha(new String(txt_confirmaSenha.getPassword()));
    }

    private void setEnableBotoes(boolean b) {
        this.btn_alterar.setEnabled(b);
        this.btn_sair.setEnabled(b);
    }
}
