/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SomarChequeForm.java
 *
 * Created on 29/11/2011, 23:34:50
 */
package br.com.controlcheque.client.telas;

import br.com.controlcheque.client.ServicesImpl.ChequeServerImpl;
import br.com.controlcheque.client.util.MetodosUtil;
import br.com.controlcheque.client.util.formata.FormataData;
import br.com.controlcheque.service.ValorCheque;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Diego
 */
public class SomarChequeForm extends BaseForm {

    private DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    private Date dataInicialPesquisa = null;
    private Date dataFinalPesquisa = null;

    /**
     * Creates new form SomarChequeForm
     */
    public SomarChequeForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_dataInicial = new javax.swing.JLabel();
        lbl_dataFinal = new javax.swing.JLabel();
        lbl_a = new javax.swing.JLabel();
        txt_numeroCheque = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_Buscar = new javax.swing.JButton();
        txt_valor = new javax.swing.JFormattedTextField();
        txtf_dataInicial = new javax.swing.JTextField();
        txtf_dataFinal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbl_buscaClientes2 = new javax.swing.JLabel();
        lbl_buscaClientes3 = new javax.swing.JLabel();
        btn_limpar = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Somar cheques em Mãos");
        setMinimumSize(new java.awt.Dimension(350, 285));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEtchedBorder()), "Somar entre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(43, 116, 185))); // NOI18N
        jPanel1.setLayout(null);

        lbl_dataInicial.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl_dataInicial.setText("Data Inicial");
        jPanel1.add(lbl_dataInicial);
        lbl_dataInicial.setBounds(18, 34, 62, 15);

        lbl_dataFinal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl_dataFinal.setText("Data Final");
        jPanel1.add(lbl_dataFinal);
        lbl_dataFinal.setBounds(131, 34, 55, 15);

        lbl_a.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl_a.setText("à");
        jPanel1.add(lbl_a);
        lbl_a.setBounds(105, 55, 12, 15);

        txt_numeroCheque.setBackground(new java.awt.Color(0, 0, 0));
        txt_numeroCheque.setEditable(false);
        txt_numeroCheque.setForeground(new java.awt.Color(255, 255, 255));
        txt_numeroCheque.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(txt_numeroCheque);
        txt_numeroCheque.setBounds(150, 100, 80, 21);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Número de Cheques:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 100, 118, 15);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Valor:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 130, 33, 15);

        btn_Buscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/16x16/accessories-calculator.png"))); // NOI18N
        btn_Buscar.setText("Somar");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Buscar);
        btn_Buscar.setBounds(240, 40, 90, 40);

        txt_valor.setBackground(new java.awt.Color(0, 0, 0));
        txt_valor.setEditable(false);
        txt_valor.setForeground(new java.awt.Color(255, 255, 255));
        txt_valor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txt_valor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(txt_valor);
        txt_valor.setBounds(150, 130, 80, 21);

        txtf_dataInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_dataInicialActionPerformed(evt);
            }
        });
        txtf_dataInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtf_dataInicialKeyPressed(evt);
            }
        });
        jPanel1.add(txtf_dataInicial);
        txtf_dataInicial.setBounds(18, 55, 70, 20);
        txtf_dataInicial.setDocument(new FormataData());

        txtf_dataFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtf_dataFinalKeyPressed(evt);
            }
        });
        jPanel1.add(txtf_dataFinal);
        txtf_dataFinal.setBounds(130, 55, 80, 20);
        txtf_dataFinal.setDocument(new FormataData());

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 346, 177);

        jPanel2.setBackground(new java.awt.Color(178, 179, 180));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEtchedBorder()));

        lbl_buscaClientes2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl_buscaClientes2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_buscaClientes2.setText("F4: Limpar");

        lbl_buscaClientes3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl_buscaClientes3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_buscaClientes3.setText("Esc: Sair");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbl_buscaClientes2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(lbl_buscaClientes3)
                .addGap(68, 68, 68))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_buscaClientes3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_buscaClientes2))
                .addGap(129, 129, 129))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 230, 340, 25);

        btn_limpar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/edit-clear.png"))); // NOI18N
        btn_limpar.setText("Limpar");
        btn_limpar.setPreferredSize(new java.awt.Dimension(150, 40));
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limpar);
        btn_limpar.setBounds(0, 180, 120, 40);

        btn_sair.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/sair32x32.png"))); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.setPreferredSize(new java.awt.Dimension(150, 40));
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sair);
        btn_sair.setBounds(220, 180, 120, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        // TODO add your handling code here:
        if (validateForm()
                && validaData()) {
            buscarValorCheque();
        }
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void txtf_dataInicialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_dataInicialKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_dataInicialKeyPressed

    private void txtf_dataFinalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_dataFinalKeyPressed
        // TODO add your handling code here:        
    }//GEN-LAST:event_txtf_dataFinalKeyPressed

    private void txtf_dataInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_dataInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_dataInicialActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_btn_sairActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_a;
    private javax.swing.JLabel lbl_buscaClientes2;
    private javax.swing.JLabel lbl_buscaClientes3;
    private javax.swing.JLabel lbl_dataFinal;
    private javax.swing.JLabel lbl_dataInicial;
    private javax.swing.JFormattedTextField txt_numeroCheque;
    private javax.swing.JFormattedTextField txt_valor;
    private javax.swing.JTextField txtf_dataFinal;
    private javax.swing.JTextField txtf_dataInicial;
    // End of variables declaration//GEN-END:variables

    /**
     * fecha formulario
     */
    private void close() {
        this.dispose();
    }

    /**
     * limpa formulario
     */
    private void clear() {
        txtf_dataInicial.setText("");
        txtf_dataFinal.setText("");
        txt_valor.setText("");
        txt_numeroCheque.setText("");
    }

    /**
     * valida os campos obrigatorios
     *
     * @return
     */
    private boolean validateForm() {

        String msgErro = "";

        if (txtf_dataInicial.getText().replace("/", "").trim().isEmpty()) {
            msgErro = "Campo data inicial em branco.";
        }

        if (txtf_dataFinal.getText().replace("/", "").trim().isEmpty()) {
            if (!msgErro.isEmpty()) {
                msgErro += "\n";
            }

            msgErro += "Campo data final em branco.";
        }

        if (!msgErro.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, msgErro, "Atenção", 2);
            return false;
        }
        return true;
    }

    /**
     * Valida data informada
     *
     * @param data
     * @return
     */
    private boolean validaData() {
        try {
            dataInicialPesquisa = df.parse(txtf_dataInicial.getText());
            dataFinalPesquisa = df.parse(txtf_dataFinal.getText());
            return true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data" + " inválida.", "Erro", 0);
            return false;
        }
    }

    private void buscarValorCheque() {
        final JDialogProcessando aguarde = new JDialogProcessando(this, "Aguarde...", "Aguarde Processando...");
        aguarde.setVisible(true);

        SwingWorker<ValorCheque, Void> worker = new SwingWorker<ValorCheque, Void>() {

            @Override
            protected ValorCheque doInBackground() throws Exception {
                ValorCheque retorno = null;
                try {
                    retorno = new ChequeServerImpl().recValorChequePorIntervaloData(dataInicialPesquisa, dataFinalPesquisa);
                } catch (Exception ex) {
                    aguarde.setVisible(false);
                    throw ex;
                }

                return retorno;

            }

            @Override
            protected void done() {
                aguarde.setVisible(false);
                try {
                    ValorCheque result = (ValorCheque) get();
                    txt_valor.setText("R$ " + MetodosUtil.convertFloatToString(result.getValor()));
                    txt_numeroCheque.setText(Integer.toString(result.getQuantidade()));

                } catch (Exception ex) {
                    tratarErro(SomarChequeForm.class, ex);
                }
            }
        };

        worker.execute();

    }
}
