/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaPrincipalForm.java
 *
 * Created on 29/11/2011, 23:33:42
 */
package br.com.controlcheque.client.telas;

import br.com.controlcheque.client.App;
import br.com.controlcheque.client.Enum.EnumSituacaoCheque;
import br.com.controlcheque.client.Excecao.ClientChequeException;
import br.com.controlcheque.client.ServicesImpl.BancoServerImpl;
import br.com.controlcheque.client.ServicesImpl.ChequeServerImpl;
import br.com.controlcheque.client.ServicesImpl.ClienteServerImpl;
import br.com.controlcheque.client.ServicesImpl.UtilServerImpl;
import br.com.controlcheque.client.util.ClientConstantes;
import br.com.controlcheque.client.util.DadosCadastroCheque;
import br.com.controlcheque.client.util.UtilServiceCheque;
import br.com.controlcheque.service.Banco;
import br.com.controlcheque.service.Cheque;
import br.com.controlcheque.service.Cliente;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Diego
 */
public class TelaPrincipalForm extends BaseForm {

    /**
     * Atributos da classe
     */
    private CadastroClienteForm formCadastroCliente = null;
    private ConsultaClienteForm formConsultarCliente = null;
    private CadastroChequesForm formCadastroCheque = null;
    private ConsultarChequesForm formConsultaCheque = null;
    private CadastroBancosForm formCadastroBanco = null;
    private ConsultaBancoForm formConsultaBanco = null;
    private LixeiraForm formLixeiraCheques = null;

    /**
     * METODOS ACESSORES
     *
     * @return
     */
    public CadastroClienteForm getFormCadastroCliente() {
        return formCadastroCliente;
    }

    public void setFormCadastroCliente(CadastroClienteForm formCadastroCliente) {
        this.formCadastroCliente = formCadastroCliente;
    }

    public ConsultaClienteForm getFormConsultarCliente() {
        return formConsultarCliente;
    }

    public void setFormConsultarCliente(ConsultaClienteForm formConsultarCliente) {
        this.formConsultarCliente = formConsultarCliente;
    }

    public CadastroBancosForm getFormCadastroBanco() {
        return formCadastroBanco;
    }

    public void setFormCadastroBanco(CadastroBancosForm formCadastroBanco) {
        this.formCadastroBanco = formCadastroBanco;
    }

    public CadastroChequesForm getFormCadastroCheque() {
        return formCadastroCheque;
    }

    public void setFormCadastroCheque(CadastroChequesForm formCadastroCheque) {
        this.formCadastroCheque = formCadastroCheque;
    }

    public ConsultaBancoForm getFormConsultaBanco() {
        return formConsultaBanco;
    }

    public void setFormConsultaBanco(ConsultaBancoForm formConsultaBanco) {
        this.formConsultaBanco = formConsultaBanco;
    }

    public LixeiraForm getFormLixeiraCheques() {
        return formLixeiraCheques;
    }

    public void setFormLixeiraCheques(LixeiraForm formLixeiraCheques) {
        this.formLixeiraCheques = formLixeiraCheques;
    }

    /**
     * FIM METODOS ACESSORES
     */
    /**
     * Creates new form TelaPrincipalForm
     */
    public TelaPrincipalForm() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        controleAcesso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cadCliente = new javax.swing.JButton();
        btn_cadCheque = new javax.swing.JButton();
        btn_todosCheques = new javax.swing.JButton();
        btn_chequesDevolvidos = new javax.swing.JButton();
        btn_chequesEmMaos = new javax.swing.JButton();
        btn_chequesRepassados = new javax.swing.JButton();
        btn_pesquisarCliente = new javax.swing.JButton();
        btn_cadBanco = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        menuBarCheque = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemArquivoSair = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuCheque = new javax.swing.JMenu();
        jMenuItemChequeCadastrar = new javax.swing.JMenuItem();
        jMenuChequeManutencao = new javax.swing.JMenu();
        jMenuItemTodosCheques = new javax.swing.JMenuItem();
        jMenuItemChequesDevolvidos = new javax.swing.JMenuItem();
        jMenuItemEmMaos = new javax.swing.JMenuItem();
        jMenuItemChequesRepassados = new javax.swing.JMenuItem();
        jMenuItemChequeSomar = new javax.swing.JMenuItem();
        jMenuItemChequeLixeira = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenu();
        jMenuItemClienteCadastrar = new javax.swing.JMenuItem();
        jMenuItemClienteManutencao = new javax.swing.JMenuItem();
        jMenuBanco = new javax.swing.JMenu();
        jMenuItemBancoCadastrar = new javax.swing.JMenuItem();
        jMenuItemBancoManutencao = new javax.swing.JMenuItem();
        jMenuConfigurar = new javax.swing.JMenu();
        jMenuItemConfigurarSenha = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Cheques - Modo Administrador");
        setBackground(new java.awt.Color(51, 255, 0));

        btn_cadCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_cadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/22x22/clientADD.png"))); // NOI18N
        btn_cadCliente.setMnemonic(112);
        btn_cadCliente.setText("Cad. Cliente");
        btn_cadCliente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_cadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadClienteActionPerformed(evt);
            }
        });

        btn_cadCheque.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_cadCheque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/22x22/notaADD.png"))); // NOI18N
        btn_cadCheque.setText("Cad. Cheque");
        btn_cadCheque.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_cadCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadChequeActionPerformed(evt);
            }
        });

        btn_todosCheques.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_todosCheques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/22x22/editar-consultar.png"))); // NOI18N
        btn_todosCheques.setText("Todos Cheques");
        btn_todosCheques.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_todosCheques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_todosChequesActionPerformed(evt);
            }
        });

        btn_chequesDevolvidos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_chequesDevolvidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/22x22/notaEDIT.png"))); // NOI18N
        btn_chequesDevolvidos.setText("Cheques Devolvidos");
        btn_chequesDevolvidos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_chequesDevolvidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chequesDevolvidosActionPerformed(evt);
            }
        });

        btn_chequesEmMaos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_chequesEmMaos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/22x22/notaEDIT.png"))); // NOI18N
        btn_chequesEmMaos.setText("Cheques em Mãos");
        btn_chequesEmMaos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_chequesEmMaos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chequesEmMaosActionPerformed(evt);
            }
        });

        btn_chequesRepassados.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_chequesRepassados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/22x22/notaEDIT.png"))); // NOI18N
        btn_chequesRepassados.setText("Cheques Repassados");
        btn_chequesRepassados.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_chequesRepassados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chequesRepassadosActionPerformed(evt);
            }
        });

        btn_pesquisarCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_pesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/22x22/clientSEARCH.png"))); // NOI18N
        btn_pesquisarCliente.setText("Pesquisar Cliente");
        btn_pesquisarCliente.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btn_pesquisarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_pesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarClienteActionPerformed(evt);
            }
        });

        btn_cadBanco.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_cadBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/22x22/novo.png"))); // NOI18N
        btn_cadBanco.setText("Cad. Banco");
        btn_cadBanco.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_cadBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadBancoActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(178, 179, 180));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEtchedBorder()));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("F1: Cadastrar Cliente");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("F2: Cadastrar Cheque");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("F6: Todos os Cheques");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("F7: Cheques Devolvidos");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("F8: Cheques em Mãos");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("F9: Cheques Repassados");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("F11: Pesquisar Clientes");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("F12: Cadastrar Banco");

        jPanel2.setBackground(new java.awt.Color(178, 179, 180));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(178, 179, 180));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(178, 179, 180));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addGap(45, 45, 45)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );

        menuBarCheque.setBackground(new java.awt.Color(43, 116, 185));

        jMenuArquivo.setBackground(new java.awt.Color(43, 116, 185));
        jMenuArquivo.setForeground(new java.awt.Color(255, 255, 255));
        jMenuArquivo.setText("Arquivo");
        jMenuArquivo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItemArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

            }
        });
        jMenuItemArquivoSair.setText("Sair");
        jMenuItemArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemArquivoSairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemArquivoSair);

        jMenuItem1.setText("Backup");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItem1);

        menuBarCheque.add(jMenuArquivo);

        jMenuCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

            }
        });
        jMenuCheque.setBackground(new java.awt.Color(43, 116, 185));
        jMenuCheque.setForeground(new java.awt.Color(255, 255, 255));
        jMenuCheque.setText("Cheque");
        jMenuCheque.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItemChequeCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //        CadastroChequesForm cadastroCheque = new CadastroChequesForm();
                //        cadastroCheque.setVisible(true);
            }
        });
        jMenuItemChequeCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItemChequeCadastrar.setText("Cadastrar");
        jMenuItemChequeCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemChequeCadastrarActionPerformed(evt);
            }
        });
        jMenuCheque.add(jMenuItemChequeCadastrar);

        jMenuChequeManutencao.setText("Manutenção de");

        jMenuItemTodosCheques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //br.com.controlcheque.client.telas.ConsultarChequesForm tela = new br.com.controlcheque.client.telas.ConsultarChequesForm();
                //tela.setVisible(true);
            }
        });
        jMenuItemTodosCheques.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItemTodosCheques.setText("Todos os Cheques");
        jMenuItemTodosCheques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTodosChequesActionPerformed(evt);
            }
        });
        jMenuChequeManutencao.add(jMenuItemTodosCheques);

        jMenuItemChequesDevolvidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // br.com.controlcheque.client.telas.ConsultarChequesForm tela = new br.com.controlcheque.client.telas.ConsultarChequesForm();
                //tela.setVisible(true);
            }
        });
        jMenuItemChequesDevolvidos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItemChequesDevolvidos.setText("Cheques Devolvidos");
        jMenuItemChequesDevolvidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemChequesDevolvidosActionPerformed(evt);
            }
        });
        jMenuChequeManutencao.add(jMenuItemChequesDevolvidos);

        jMenuItemEmMaos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // br.com.controlcheque.client.telas.ConsultarChequesForm tela = new br.com.controlcheque.client.telas.ConsultarChequesForm();
                // tela.setVisible(true);
            }
        });
        jMenuItemEmMaos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jMenuItemEmMaos.setText("Cheques em Mãos");
        jMenuItemEmMaos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEmMaosActionPerformed(evt);
            }
        });
        jMenuChequeManutencao.add(jMenuItemEmMaos);

        jMenuItemChequesRepassados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //br.com.controlcheque.client.telas.ConsultarChequesForm tela = new br.com.controlcheque.client.telas.ConsultarChequesForm();
                //tela.setVisible(true);
            }
        });
        jMenuItemChequesRepassados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMenuItemChequesRepassados.setText("Cheques Repassados");
        jMenuItemChequesRepassados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemChequesRepassadosActionPerformed(evt);
            }
        });
        jMenuChequeManutencao.add(jMenuItemChequesRepassados);

        jMenuCheque.add(jMenuChequeManutencao);

        jMenuItemChequeSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SomarChequeForm tela = new SomarChequeForm();
                tela.setVisible(true);
            }
        });
        jMenuItemChequeSomar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemChequeSomar.setText("Somar entre datas");
        jMenuCheque.add(jMenuItemChequeSomar);

        jMenuItemChequeLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openLixeiraForm();
            }
        });
        jMenuItemChequeLixeira.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemChequeLixeira.setText("Lixeira");
        jMenuCheque.add(jMenuItemChequeLixeira);

        menuBarCheque.add(jMenuCheque);

        jMenuCliente.setBackground(new java.awt.Color(43, 116, 185));
        jMenuCliente.setForeground(new java.awt.Color(255, 255, 255));
        jMenuCliente.setText("Cliente");
        jMenuCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItemClienteCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCliente();
            }
        });
        jMenuItemClienteCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItemClienteCadastrar.setText("Cadastrar");
        jMenuItemClienteCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteCadastrarActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemClienteCadastrar);

        jMenuItemClienteManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarClientes();
            }
        });
        jMenuItemClienteManutencao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        jMenuItemClienteManutencao.setText("Manutenção");
        jMenuCliente.add(jMenuItemClienteManutencao);

        menuBarCheque.add(jMenuCliente);

        jMenuBanco.setBackground(new java.awt.Color(43, 116, 185));
        jMenuBanco.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBanco.setText("Banco");
        jMenuBanco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItemBancoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBanco();
            }
        });
        jMenuItemBancoCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItemBancoCadastrar.setText("Cadastrar");
        jMenuBanco.add(jMenuItemBancoCadastrar);

        jMenuItemBancoManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBancos();
            }
        });
        jMenuItemBancoManutencao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemBancoManutencao.setText("Consultar");
        jMenuBanco.add(jMenuItemBancoManutencao);

        menuBarCheque.add(jMenuBanco);

        jMenuConfigurar.setBackground(new java.awt.Color(43, 116, 185));
        jMenuConfigurar.setForeground(new java.awt.Color(255, 255, 255));
        jMenuConfigurar.setText("Configurar");
        jMenuConfigurar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItemConfigurarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarSenhasForm tela = new AlterarSenhasForm();
                tela.setVisible(true);
            }
        });
        jMenuItemConfigurarSenha.setText("Alterar Senha");
        jMenuConfigurar.add(jMenuItemConfigurarSenha);

        menuBarCheque.add(jMenuConfigurar);

        setJMenuBar(menuBarCheque);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btn_cadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cadCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_todosCheques, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_chequesDevolvidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_chequesEmMaos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_chequesRepassados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_pesquisarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cadBanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_todosCheques, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_chequesDevolvidos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_chequesEmMaos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_chequesRepassados, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarCheques(int situacao) {
        final int situacaoCheque = situacao;
        final JDialogProcessando aguarde = new JDialogProcessando(this, "Aguarde...", "Aguarde Processando...");
        aguarde.setVisible(true);
        SwingWorker<Object, Void> worker = new SwingWorker<Object, Void>() {

            @Override
            protected Object doInBackground() throws Exception {
                try {
                    DadosCadastroCheque dadosCheque = new DadosCadastroCheque();
                    dadosCheque.setLstCheques(new UtilServiceCheque().recChequeDoInBackground(situacaoCheque));
                    dadosCheque.setLstClientes(DadosCadastroCheque.buscaListaCliente());
                    return dadosCheque;
                } catch (Exception ex) {
                    aguarde.setVisible(false);
                    throw ex;
                }

            }

            @Override
            protected void done() {
                aguarde.setVisible(false);
                try {
                    DadosCadastroCheque result = (DadosCadastroCheque) get();
                    if (formConsultaCheque != null) {
                        formConsultaCheque.dispose();
                    }
                    formConsultaCheque = new ConsultarChequesForm();
                    formConsultaCheque.setSituacaoCheque(situacaoCheque);
                    formConsultaCheque.setListaCheques(result.getLstCheques());
                    formConsultaCheque.setListaClientesPasseiPara(result.getLstClientes());
                    formConsultaCheque.showFrame();
                } catch (Exception ex) {
                    tratarErro(TelaPrincipalForm.class, ex);
                }
            }
        };

        worker.execute();

    }

    private void consultarClientes() {
        final JDialogProcessando aguarde = new JDialogProcessando(this, "Aguarde...", "Aguarde Processando...");
        aguarde.setVisible(true);

        SwingWorker<Object, Void> worker = new SwingWorker<Object, Void>() {

            @Override
            protected Object doInBackground() throws Exception {
                List<Cliente> lstClientes = null;
                try {
                    lstClientes = new ClienteServerImpl().recTodos();
                } catch (Exception ex) {
                    aguarde.setVisible(false);
                    throw ex;
                }

                return lstClientes;

            }

            @Override
            protected void done() {
                aguarde.setVisible(false);
                try {
                    List<Cliente> result = (List<Cliente>) get();
                    if (formConsultarCliente == null) {
                        formConsultarCliente = new ConsultaClienteForm();
                    }
                    formConsultarCliente.setLstClientes(result);
                    formConsultarCliente.showFrame();
                } catch (Exception ex) {
                    tratarErro(TelaPrincipalForm.class, ex);
                }
            }
        };

        worker.execute();
    }

    private void consultarBancos() {

        final JDialogProcessando aguarde = new JDialogProcessando(this, "Aguarde...", "Aguarde Processando...");
        aguarde.setVisible(true);

        SwingWorker<Object, Void> worker = new SwingWorker<Object, Void>() {

            @Override
            protected Object doInBackground() throws Exception {
                List<Banco> lstBancos = null;
                try {
                    lstBancos = new BancoServerImpl().recTodos();
                } catch (Exception ex) {
                    aguarde.setVisible(false);
                    throw ex;
                }

                return lstBancos;

            }

            @Override
            protected void done() {
                aguarde.setVisible(false);
                try {
                    List<Banco> result = (List<Banco>) get();
                    if (formConsultaBanco == null) {
                        formConsultaBanco = new ConsultaBancoForm();
                    }
                    formConsultaBanco.setG_listaBancos(result);
                    formConsultaBanco.showFrame();
                } catch (Exception ex) {
                    tratarErro(TelaPrincipalForm.class, ex);
                }
            }
        };

        worker.execute();
    }

    private void cadastrarBanco() {
        try {
            if (formCadastroBanco == null) {
                formCadastroBanco = new CadastroBancosForm();
            }
            formCadastroBanco.showFrame();
        } catch (Exception ex) {
            tratarErro(TelaPrincipalForm.class, ex);
        }
    }

    private void cadastrarCliente() {
        final JDialogProcessando aguarde = new JDialogProcessando(this, "Aguarde...", "Aguarde Processando...");
        aguarde.setVisible(true);

        SwingWorker<Object, Void> worker = new SwingWorker<Object, Void>() {

            @Override
            protected Object doInBackground() throws Exception {
                String codigo = null;
                try {
                    ClienteServerImpl clienteServer = new ClienteServerImpl();
                    codigo = clienteServer.gerarCodigoCliente();
                } catch (Exception ex) {
                    aguarde.setVisible(false);
                    throw ex;
                }

                return codigo;
            }

            @Override
            protected void done() {
                aguarde.setVisible(false);
                try {
                    String codigo = (String) get();
                    if (formCadastroCliente == null) {
                        formCadastroCliente = new CadastroClienteForm(codigo);
                    }
                    formCadastroCliente.showFrame();
                } catch (Exception ex) {
                    tratarErro(TelaPrincipalForm.class, ex);
                }
            }
        };

        worker.execute();

    }

    private void cadastrarCheque() {
        final JDialogProcessando aguarde = new JDialogProcessando(this, "Aguarde...", "Aguarde Processando...");
        aguarde.setVisible(true);

        SwingWorker<Object, Void> worker = new SwingWorker<Object, Void>() {

            @Override
            protected Object doInBackground() throws Exception {
                DadosCadastroCheque dadosCheque = null;
                try {
                    dadosCheque = DadosCadastroCheque.getDadosCadastroCheque();
                } catch (Exception ex) {
                    aguarde.setVisible(false);
                    throw ex;
                }

                return dadosCheque;
            }

            @Override
            protected void done() {
                aguarde.setVisible(false);
                try {
                    DadosCadastroCheque dadosCheque = (DadosCadastroCheque) get();
                    if (formCadastroCheque == null) {
                        formCadastroCheque = new CadastroChequesForm();
                    }
                    formCadastroCheque.setCheque(new Cheque());
                    formCadastroCheque.setCodigo(dadosCheque.getCodigo());
                    formCadastroCheque.setListBancos(dadosCheque.getLstBancos());
                    formCadastroCheque.setListClientes(dadosCheque.getLstClientes());
                    formCadastroCheque.showFrame();
                } catch (Exception ex) {
                    tratarErro(TelaPrincipalForm.class, ex);
                }
            }
        };

        worker.execute();

    }

    private void openLixeiraForm() {
        final JDialogProcessando aguarde = new JDialogProcessando(this, "Aguarde...", "Aguarde Processando...");
        aguarde.setVisible(true);
        SwingWorker<List<Cheque>, Void> worker = new SwingWorker<List<Cheque>, Void>() {

            @Override
            protected List<Cheque> doInBackground() throws Exception {
                try {
                    return new ChequeServerImpl().recChequesRemovidos();
                } catch (Exception ex) {
                    aguarde.setVisible(false);
                    throw ex;
                }

            }

            @Override
            protected void done() {
                aguarde.setVisible(false);
                try {
                    List<Cheque> result = (List<Cheque>) get();
                    if (formLixeiraCheques == null) {
                        formLixeiraCheques = new LixeiraForm();
                    }
                    formLixeiraCheques.setListaChequesRemovidos(result);
                    formLixeiraCheques.showFrame();
                } catch (Exception ex) {
                    tratarErro(TelaPrincipalForm.class, ex);
                }
            }
        };

        worker.execute();
    }

    private void btn_cadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadClienteActionPerformed
        cadastrarCliente();
    }//GEN-LAST:event_btn_cadClienteActionPerformed

    private void btn_cadChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadChequeActionPerformed
        cadastrarCheque();
    }//GEN-LAST:event_btn_cadChequeActionPerformed

    private void btn_cadBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadBancoActionPerformed

        cadastrarBanco();
    }//GEN-LAST:event_btn_cadBancoActionPerformed

    private void btn_pesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarClienteActionPerformed
        consultarClientes();
    }//GEN-LAST:event_btn_pesquisarClienteActionPerformed

    private void btn_chequesEmMaosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chequesEmMaosActionPerformed
        consultarCheques(EnumSituacaoCheque.EmMaos.getCodigo());
    }//GEN-LAST:event_btn_chequesEmMaosActionPerformed

    private void btn_todosChequesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_todosChequesActionPerformed
        consultarCheques(EnumSituacaoCheque.Todos.getCodigo());
    }//GEN-LAST:event_btn_todosChequesActionPerformed

    private void btn_chequesDevolvidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chequesDevolvidosActionPerformed
        consultarCheques(EnumSituacaoCheque.Devolvido.getCodigo());
    }//GEN-LAST:event_btn_chequesDevolvidosActionPerformed

    private void btn_chequesRepassadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chequesRepassadosActionPerformed
        consultarCheques(EnumSituacaoCheque.Repassado.getCodigo());
    }//GEN-LAST:event_btn_chequesRepassadosActionPerformed

    private void jMenuItemChequeCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemChequeCadastrarActionPerformed
        // TODO add your handling code here:
        cadastrarCheque();
    }//GEN-LAST:event_jMenuItemChequeCadastrarActionPerformed

    private void jMenuItemClienteCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteCadastrarActionPerformed
        // TODO add your handling code here:
        cadastrarCliente();
    }//GEN-LAST:event_jMenuItemClienteCadastrarActionPerformed

    private void jMenuItemTodosChequesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTodosChequesActionPerformed
        // TODO add your handling code here:
        consultarCheques(EnumSituacaoCheque.Todos.getCodigo());
    }//GEN-LAST:event_jMenuItemTodosChequesActionPerformed

    private void jMenuItemChequesDevolvidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemChequesDevolvidosActionPerformed
        // TODO add your handling code here:
        consultarCheques(EnumSituacaoCheque.Devolvido.getCodigo());
    }//GEN-LAST:event_jMenuItemChequesDevolvidosActionPerformed

    private void jMenuItemEmMaosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEmMaosActionPerformed
        // TODO add your handling code here:
        consultarCheques(EnumSituacaoCheque.EmMaos.getCodigo());
    }//GEN-LAST:event_jMenuItemEmMaosActionPerformed

    private void jMenuItemChequesRepassadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemChequesRepassadosActionPerformed
        // TODO add your handling code here:
        consultarCheques(EnumSituacaoCheque.Repassado.getCodigo());
    }//GEN-LAST:event_jMenuItemChequesRepassadosActionPerformed

    private void jMenuItemArquivoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemArquivoSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItemArquivoSairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        gerarBackup();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadBanco;
    private javax.swing.JButton btn_cadCheque;
    private javax.swing.JButton btn_cadCliente;
    private javax.swing.JButton btn_chequesDevolvidos;
    private javax.swing.JButton btn_chequesEmMaos;
    private javax.swing.JButton btn_chequesRepassados;
    private javax.swing.JButton btn_pesquisarCliente;
    private javax.swing.JButton btn_todosCheques;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenu jMenuBanco;
    private javax.swing.JMenu jMenuCheque;
    private javax.swing.JMenu jMenuChequeManutencao;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenu jMenuConfigurar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemArquivoSair;
    private javax.swing.JMenuItem jMenuItemBancoCadastrar;
    private javax.swing.JMenuItem jMenuItemBancoManutencao;
    private javax.swing.JMenuItem jMenuItemChequeCadastrar;
    private javax.swing.JMenuItem jMenuItemChequeLixeira;
    private javax.swing.JMenuItem jMenuItemChequeSomar;
    private javax.swing.JMenuItem jMenuItemChequesDevolvidos;
    private javax.swing.JMenuItem jMenuItemChequesRepassados;
    private javax.swing.JMenuItem jMenuItemClienteCadastrar;
    private javax.swing.JMenuItem jMenuItemClienteManutencao;
    private javax.swing.JMenuItem jMenuItemConfigurarSenha;
    private javax.swing.JMenuItem jMenuItemEmMaos;
    private javax.swing.JMenuItem jMenuItemTodosCheques;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenuBar menuBarCheque;
    // End of variables declaration//GEN-END:variables

    private void controleAcesso() {
        if (App.usuarioLogado.getNivelAcesso().equals(ClientConstantes.NIVEL_ACESSO_FUNCIONARIO)) {
            boolean isVisible = false;
            jMenuConfigurar.setVisible(isVisible);
            jMenuItemChequeSomar.setVisible(isVisible);
            jMenuItemChequeLixeira.setVisible(isVisible);
            this.setTitle("CONTROLE DE CHEQUES  - MODO FUNCIONÁRIO");
        }
    }

    private void gerarBackup() {
        WorkBackup work = new WorkBackup();
        work.setParent(this);
        work.execute();
    }

    private class WorkBackup extends SwingWorker<Object, Object> {

        private JDialogProcessando aguarde = null;//new JDialogProcessando(this, "Aguarde...", "Aguarde Processando...");
        private JFrame parent;

        public WorkBackup() {
            aguarde = new JDialogProcessando(parent, "Aguarde...", "Aguarde Processando...");
            aguarde.setVisible(true);
        }

        @Override
        protected Object doInBackground() throws Exception {
            try {
                new UtilServerImpl().gerarBackup();
                return true;
            } catch (ClientChequeException ex) {
                throw ex;
            }
        }

        @Override
        protected void done() {
            aguarde.setVisible(false);
            try {
                if (get() != null) {
                    JOptionPane.showMessageDialog(null, "BACKUP GERADO COM SUCESSO", "BACKUP", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "ERRO AO GERAR BACKUP: " + ex.getMessage(), "BACKUP", JOptionPane.ERROR_MESSAGE);
            }

        }

        public void setParent(JFrame parent) {
            this.parent = parent;
        }
    }
}
