/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SomarChequeForm.java
 *
 * Created on 29/11/2011, 23:34:50
 */
package br.com.controlcheque.client.telas;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class SomarChequeForm extends javax.swing.JFrame {

    /** Creates new form SomarChequeForm */
    public SomarChequeForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_dataInicial = new javax.swing.JLabel();
        lbl_dataFinal = new javax.swing.JLabel();
        lbl_a = new javax.swing.JLabel();
        txtf_dataInicial = new javax.swing.JFormattedTextField();
        txtf_dataFinal = new javax.swing.JFormattedTextField();
        txt_valor = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_numCheque = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        lbl_buscaClientes2 = new javax.swing.JLabel();
        lbl_buscaClientes3 = new javax.swing.JLabel();
        lbl_buscaClientes4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_somar = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Somar cheques em Mãos");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEtchedBorder()), "Somar entre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(43, 116, 185))); // NOI18N
        jPanel1.setLayout(null);

        lbl_dataInicial.setFont(new java.awt.Font("Arial", 1, 12));
        lbl_dataInicial.setText("Data Inicial");
        jPanel1.add(lbl_dataInicial);
        lbl_dataInicial.setBounds(18, 34, 62, 15);

        lbl_dataFinal.setFont(new java.awt.Font("Arial", 1, 12));
        lbl_dataFinal.setText("Data Final");
        jPanel1.add(lbl_dataFinal);
        lbl_dataFinal.setBounds(131, 34, 55, 15);

        lbl_a.setFont(new java.awt.Font("Arial", 1, 12));
        lbl_a.setText("à");
        jPanel1.add(lbl_a);
        lbl_a.setBounds(113, 62, 12, 15);

        try {
            txtf_dataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtf_dataInicial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtf_dataInicialFocusLost(evt);
            }
        });
        jPanel1.add(txtf_dataInicial);
        txtf_dataInicial.setBounds(18, 60, 85, 20);

        try {
            txtf_dataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtf_dataFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtf_dataFinalFocusLost(evt);
            }
        });
        jPanel1.add(txtf_dataFinal);
        txtf_dataFinal.setBounds(131, 60, 89, 20);

        txt_valor.setBackground(new java.awt.Color(0, 0, 0));
        txt_valor.setEditable(false);
        txt_valor.setForeground(new java.awt.Color(255, 255, 255));
        txt_valor.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel1.add(txt_valor);
        txt_valor.setBounds(363, 34, 110, 21);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel5.setText("Número de Cheques:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(276, 69, 118, 15);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel4.setText("Valor:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(320, 37, 33, 15);

        txt_numCheque.setBackground(new java.awt.Color(0, 0, 0));
        txt_numCheque.setEditable(false);
        txt_numCheque.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txt_numCheque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_numCheque.setFont(new java.awt.Font("Arial", 1, 12));
        jPanel1.add(txt_numCheque);
        txt_numCheque.setBounds(404, 66, 118, 21);

        jPanel2.setBackground(new java.awt.Color(178, 179, 180));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEtchedBorder()));

        lbl_buscaClientes2.setFont(new java.awt.Font("Arial", 1, 12));
        lbl_buscaClientes2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_buscaClientes2.setText("F4: Limpar");

        lbl_buscaClientes3.setFont(new java.awt.Font("Arial", 1, 12));
        lbl_buscaClientes3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_buscaClientes3.setText("Esc: Sair");

        lbl_buscaClientes4.setFont(new java.awt.Font("Arial", 1, 12));
        lbl_buscaClientes4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_buscaClientes4.setText("Enter: Gravar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lbl_buscaClientes4)
                .addGap(129, 129, 129)
                .addComponent(lbl_buscaClientes2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(lbl_buscaClientes3)
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_buscaClientes4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_buscaClientes3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_buscaClientes2))
                .addGap(129, 129, 129))
        );

        jPanel3.setLayout(null);

        btn_somar.setFont(new java.awt.Font("Arial", 0, 12));
        btn_somar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/16x16/accessories-calculator.png"))); // NOI18N
        btn_somar.setText("Somar");
        btn_somar.setPreferredSize(new java.awt.Dimension(150, 40));
        btn_somar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_somarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_somar);
        btn_somar.setBounds(10, 0, 150, 41);

        btn_limpar.setFont(new java.awt.Font("Arial", 0, 12));
        btn_limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/edit-clear.png"))); // NOI18N
        btn_limpar.setText("Limpar");
        btn_limpar.setPreferredSize(new java.awt.Dimension(150, 40));
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });
        jPanel3.add(btn_limpar);
        btn_limpar.setBounds(203, 0, 150, 41);

        btn_sair.setFont(new java.awt.Font("Arial", 0, 12));
        btn_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/sair32x32.png"))); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.setPreferredSize(new java.awt.Dimension(150, 40));
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });
        jPanel3.add(btn_sair);
        btn_sair.setBounds(395, 0, 150, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_somarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_somarActionPerformed
        // TODO add your handling code here:
        somar();
    }//GEN-LAST:event_btn_somarActionPerformed

    private void txtf_dataInicialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtf_dataInicialFocusLost
        // TODO add your handling code here:
        if(!txtf_dataInicial.getText().replace("/", "").trim().isEmpty())
            validaData(txtf_dataInicial.getText(), "Data Inicial");
    }//GEN-LAST:event_txtf_dataInicialFocusLost

    private void txtf_dataFinalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtf_dataFinalFocusLost
        // TODO add your handling code here:
        if(!txtf_dataFinal.getText().replace("/", "").trim().isEmpty())
            validaData(txtf_dataFinal.getText(), "Data Final");
    }//GEN-LAST:event_txtf_dataFinalFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SomarChequeForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_sair;
    private javax.swing.JButton btn_somar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_a;
    private javax.swing.JLabel lbl_buscaClientes2;
    private javax.swing.JLabel lbl_buscaClientes3;
    private javax.swing.JLabel lbl_buscaClientes4;
    private javax.swing.JLabel lbl_dataFinal;
    private javax.swing.JLabel lbl_dataInicial;
    private javax.swing.JFormattedTextField txt_numCheque;
    private javax.swing.JFormattedTextField txt_valor;
    private javax.swing.JFormattedTextField txtf_dataFinal;
    private javax.swing.JFormattedTextField txtf_dataInicial;
    // End of variables declaration//GEN-END:variables

    /**
     * fecha formulario
     */
    private void close(){
        this.dispose();
    }
    
    /**
     * limpa formulario
     */
    private void clear(){
        txtf_dataInicial.setText("");
        txtf_dataFinal.setText("");
        txt_valor.setText("");
        txt_numCheque.setText("");
    }
    
    /**
     * valida os campos obrigatorios
     * @return 
     */
    private boolean validateForm(){
        
        String msgErro = "";
        
        if(txtf_dataInicial.getText().replace("/", "").trim().isEmpty())
            msgErro = "Campo data inicial em branco.";
        
        if(txtf_dataFinal.getText().replace("/", "").trim().isEmpty()){
            if(!msgErro.isEmpty())
                msgErro += "\n";
                        
            msgErro += "Campo data final em branco.";
        }
        
        if(!msgErro.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, msgErro, "Atenção", 2);
            return false;
        }
        return true;
    }
    
    /**
     * recupera os items dá tela
     */
    private void pushToModel(){
        
    }
    
    /**
     * Somar
     */
    private void somar(){
        
        if(validateForm()){
            pushToModel();
            
        }
    }
    
    /**
     * busca os cheques no periodo passado e realiza os calculos
     * @return 
     */
    private boolean somarCheques(){
        return true;
    }
    
    /**
     * popula na tela o resultado do calculo obtido
     * @param valor
     * @param numCheque 
     */
    private void populaResultado(String valor, String numCheque){
        txt_valor.setText(valor);
        txt_numCheque.setText(numCheque);
        
    }
    
    /**
     * Valida data informada
     * @param data
     * @return 
     */
    private void validaData(String data, String nomeCampo){
        try {
            new Date(data);
        } catch (Exception e) {            
            JOptionPane.showMessageDialog(rootPane, nomeCampo + " inválida.", "Erro", 0);
        }
    }

}
