/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaPrincipalForm.java
 *
 * Created on 29/11/2011, 23:33:42
 */
package br.com.controlcheque.client.telas;

import br.com.controlcheque.client.Enum.EnumSituacaoCheque;
import br.com.controlcheque.client.mensagem.MensagemClientBanco;
import br.com.controlcheque.client.util.LogUtil;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Diego
 */
public class TelaPrincipalForm extends javax.swing.JFrame {

    /**
     * Atributos da classe
     */
    private CadastroClienteForm formCadastroCliente = null;
    private ConsultaClienteForm formConsultarCliente = null;
    private CadastroChequesForm formCadastroCheque = null;
    private ConsultarChequesForm formConsultaCheque = null;
    private CadastroBancosForm formCadastroBanco = null;
    private ConsultaBancoForm formConsultaBanco = null;

    /**
     * METODOS ACESSORES
     * @return 
     */
    public CadastroClienteForm getFormCadastroCliente() {
        return formCadastroCliente;
    }

    public void setFormCadastroCliente(CadastroClienteForm formCadastroCliente) {
        this.formCadastroCliente = formCadastroCliente;
    }

    public ConsultaClienteForm getFormConsultarCliente() {
        return formConsultarCliente;
    }

    public void setFormConsultarCliente(ConsultaClienteForm formConsultarCliente) {
        this.formConsultarCliente = formConsultarCliente;
    }

    public CadastroBancosForm getFormCadastroBanco() {
        return formCadastroBanco;
    }

    public void setFormCadastroBanco(CadastroBancosForm formCadastroBanco) {
        this.formCadastroBanco = formCadastroBanco;
    }

    public CadastroChequesForm getFormCadastroCheque() {
        return formCadastroCheque;
    }

    public void setFormCadastroCheque(CadastroChequesForm formCadastroCheque) {
        this.formCadastroCheque = formCadastroCheque;
    }

    public ConsultaBancoForm getFormConsultaBanco() {
        return formConsultaBanco;
    }

    public void setFormConsultaBanco(ConsultaBancoForm formConsultaBanco) {
        this.formConsultaBanco = formConsultaBanco;
    }

    public ConsultarChequesForm getFormConsultaCheque() {
        return formConsultaCheque;
    }

    public void setFormConsultaCheque(ConsultarChequesForm formConsultaCheque) {
        this.formConsultaCheque = formConsultaCheque;
    }

    /**
     * FIM METODOS ACESSORES
     */
    /** Creates new form TelaPrincipalForm */
    public TelaPrincipalForm() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        //abrir maximiazado
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cadCliente = new javax.swing.JButton();
        btn_cadCheque = new javax.swing.JButton();
        btn_todosCheques = new javax.swing.JButton();
        btn_chequesDevolvidos = new javax.swing.JButton();
        btn_chequesEmMaos = new javax.swing.JButton();
        btn_chequesRepassados = new javax.swing.JButton();
        btn_pesquisarCliente = new javax.swing.JButton();
        btn_cadBanco = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Cheques - Modo Administrador");
        setBackground(new java.awt.Color(51, 255, 0));

        btn_cadCliente.setFont(new java.awt.Font("Arial", 1, 12));
        btn_cadCliente.setMnemonic(112);
        btn_cadCliente.setText("Cad. Cliente");
        btn_cadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadClienteActionPerformed(evt);
            }
        });

        btn_cadCheque.setFont(new java.awt.Font("Arial", 1, 12));
        btn_cadCheque.setText("Cad. Cheque");
        btn_cadCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadChequeActionPerformed(evt);
            }
        });

        btn_todosCheques.setFont(new java.awt.Font("Arial", 1, 12));
        btn_todosCheques.setText("Todos Cheques");
        btn_todosCheques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_todosChequesActionPerformed(evt);
            }
        });

        btn_chequesDevolvidos.setFont(new java.awt.Font("Arial", 1, 12));
        btn_chequesDevolvidos.setText("Cheques Devolvidos");
        btn_chequesDevolvidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chequesDevolvidosActionPerformed(evt);
            }
        });

        btn_chequesEmMaos.setFont(new java.awt.Font("Arial", 1, 12));
        btn_chequesEmMaos.setText("Cheques em Mãos");
        btn_chequesEmMaos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chequesEmMaosActionPerformed(evt);
            }
        });

        btn_chequesRepassados.setFont(new java.awt.Font("Arial", 1, 12));
        btn_chequesRepassados.setText("Cheques Repassados");
        btn_chequesRepassados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chequesRepassadosActionPerformed(evt);
            }
        });

        btn_pesquisarCliente.setFont(new java.awt.Font("Arial", 1, 12));
        btn_pesquisarCliente.setText("Pesquisar Cliente");
        btn_pesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarClienteActionPerformed(evt);
            }
        });

        btn_cadBanco.setFont(new java.awt.Font("Arial", 1, 12));
        btn_cadBanco.setText("Cad. Banco");
        btn_cadBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadBancoActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(178, 179, 180));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEtchedBorder()));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("F1: Cadastrar Cliente");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("F2: Cadastrar Cheque");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("F6: Todos os Cheques");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("F7: Cheques Devolvidos");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("F8: Cheques em Mãos");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("F9: Cheques Repassados");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("F11: Pesquisar Clientes");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("F12: Cadastrar Banco");

        jPanel2.setBackground(new java.awt.Color(178, 179, 180));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(178, 179, 180));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(178, 179, 180));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addGap(45, 45, 45)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(43, 116, 185));

        jMenu1.setBackground(new java.awt.Color(43, 116, 185));
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Arquivo");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12));

        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

            }
        });
        jMenuItem2.setText("Sair");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

            }
        });
        jMenu2.setBackground(new java.awt.Color(43, 116, 185));
        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Cheque");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12));

        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroChequesForm cadastroCheque = new CadastroChequesForm();
                cadastroCheque.setVisible(true);
            }
        });
        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem3.setText("Cadastrar");
        jMenu2.add(jMenuItem3);

        jMenu8.setText("Manutenção de");

        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //br.com.controlcheque.client.telas.ConsultarChequesForm tela = new br.com.controlcheque.client.telas.ConsultarChequesForm();
                //tela.setVisible(true);
            }
        });
        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem6.setText("Todos os Cheques");
        jMenu8.add(jMenuItem6);

        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // br.com.controlcheque.client.telas.ConsultarChequesForm tela = new br.com.controlcheque.client.telas.ConsultarChequesForm();
                //tela.setVisible(true);
            }
        });
        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItem7.setText("Cheques Devolvidos");
        jMenu8.add(jMenuItem7);

        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // br.com.controlcheque.client.telas.ConsultarChequesForm tela = new br.com.controlcheque.client.telas.ConsultarChequesForm();
                // tela.setVisible(true);
            }
        });
        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jMenuItem8.setText("Cheques em Mãos");
        jMenu8.add(jMenuItem8);

        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //br.com.controlcheque.client.telas.ConsultarChequesForm tela = new br.com.controlcheque.client.telas.ConsultarChequesForm();
                //tela.setVisible(true);
            }
        });
        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMenuItem9.setText("Cheques Repassados");
        jMenu8.add(jMenuItem9);

        jMenu2.add(jMenu8);

        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SomarChequeForm tela = new SomarChequeForm();
                tela.setVisible(true);
            }
        });
        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Somar entre datas");
        jMenu2.add(jMenuItem4);

        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LixeiraForm tela = new LixeiraForm();
                tela.setVisible(true);
            }
        });
        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Lixeira");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(43, 116, 185));
        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("Cliente");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 12));

        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (formCadastroCliente == null)
                {
                    formCadastroCliente = new CadastroClienteForm();
                }
                formCadastroCliente.setVisible(true);
            }
        });
        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem10.setText("Cadastrar");
        jMenu3.add(jMenuItem10);

        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (formConsultarCliente == null)
                {
                    formConsultarCliente = new ConsultaClienteForm();
                }
                formConsultarCliente.setVisible(true);
            }
        });
        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        jMenuItem11.setText("Manutenção");
        jMenu3.add(jMenuItem11);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(43, 116, 185));
        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setText("Banco");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 12));

        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTelaCadastroBanco();
            }
        });
        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItem12.setText("Cadastrar");
        jMenu4.add(jMenuItem12);

        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTelaConsultaBanco();
            }
        });
        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem13.setText("Consultar");
        jMenu4.add(jMenuItem13);

        jMenuBar1.add(jMenu4);

        jMenu5.setBackground(new java.awt.Color(43, 116, 185));
        jMenu5.setForeground(new java.awt.Color(255, 255, 255));
        jMenu5.setText("Configurar");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 12));

        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarSenhasForm tela = new AlterarSenhasForm();
                tela.setVisible(true);
            }
        });
        jMenuItem14.setText("Alterar Senha");
        jMenu5.add(jMenuItem14);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btn_cadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cadCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_todosCheques, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_chequesDevolvidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_chequesEmMaos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_chequesRepassados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_pesquisarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cadBanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_todosCheques, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_chequesDevolvidos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_chequesEmMaos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_chequesRepassados, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadClienteActionPerformed
        if (formCadastroCliente == null) {
            formCadastroCliente = new CadastroClienteForm();
        }
        formCadastroCliente.setVisible(true);
    }//GEN-LAST:event_btn_cadClienteActionPerformed

    private void btn_cadChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadChequeActionPerformed
        if (formCadastroCheque == null) {
            formCadastroCheque = new CadastroChequesForm();
        }
        formCadastroCheque.setVisible(true);
    }//GEN-LAST:event_btn_cadChequeActionPerformed

    private void btn_cadBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadBancoActionPerformed

        if (formCadastroBanco == null) {
            formCadastroBanco = new CadastroBancosForm();
        }
        formCadastroBanco.setVisible(true);
    }//GEN-LAST:event_btn_cadBancoActionPerformed

    private void btn_pesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarClienteActionPerformed

        if (formConsultarCliente == null) {
            formConsultarCliente = new ConsultaClienteForm();
        }
        formConsultarCliente.setVisible(true);
    }//GEN-LAST:event_btn_pesquisarClienteActionPerformed

    private void btn_chequesEmMaosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chequesEmMaosActionPerformed

        if (formConsultaCheque != null) {
            formConsultaCheque.dispose();
        }
        formConsultaCheque = new ConsultarChequesForm(EnumSituacaoCheque.EmMaos.getCodigo());
        formConsultaCheque.setVisible(true);
    }//GEN-LAST:event_btn_chequesEmMaosActionPerformed

    private void btn_todosChequesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_todosChequesActionPerformed

        if (formConsultaCheque != null) {
            formConsultaCheque.dispose();
        }
        formConsultaCheque = new ConsultarChequesForm(EnumSituacaoCheque.Todos.getCodigo());
        formConsultaCheque.setVisible(true);
    }//GEN-LAST:event_btn_todosChequesActionPerformed

    private void btn_chequesDevolvidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chequesDevolvidosActionPerformed
        if (formConsultaCheque != null) {
            formConsultaCheque.dispose();
        }
        formConsultaCheque = new ConsultarChequesForm(EnumSituacaoCheque.Devolvido.getCodigo());
        formConsultaCheque.setVisible(true);
    }//GEN-LAST:event_btn_chequesDevolvidosActionPerformed

    private void btn_chequesRepassadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chequesRepassadosActionPerformed
        if (formConsultaCheque != null) {
            formConsultaCheque.dispose();
        }
        formConsultaCheque = new ConsultarChequesForm(EnumSituacaoCheque.Repassado.getCodigo());
        formConsultaCheque.setVisible(true);
    }//GEN-LAST:event_btn_chequesRepassadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaPrincipalForm().setVisible(true);
            }
        });
    }

    private void showTelaCadastroBanco() {
        if (formCadastroBanco == null) {
            formCadastroBanco = new CadastroBancosForm();
        }

        formCadastroBanco.setVisible(true);
    }

    private void showTelaConsultaBanco() {
        final JDialogProcessando aguarde = new JDialogProcessando(this, "Aguarde...", "Processando...");
        aguarde.setVisible(true);

        try {
            new SwingWorker() {

                @Override
                protected Object doInBackground() throws Exception {
                    try {
                        if (formConsultaBanco == null) {
                            formConsultaBanco = new ConsultaBancoForm();
                        }

                    } catch (Exception ex) {
                        aguarde.dispose();
                        throw ex;
                    }
                    return null;
                }

                @Override
                protected void done() {
                    aguarde.dispose();
                    formConsultaBanco.setVisible(true);
                }
            }.execute();
        } catch (Exception ex) {
            LogUtil.logDescricaoErro(this.getClass(), ex);
            JOptionPane.showMessageDialog(rootPane, MensagemClientBanco.getMensagemErro(ex.getMessage()), "Erro", 2);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadBanco;
    private javax.swing.JButton btn_cadCheque;
    private javax.swing.JButton btn_cadCliente;
    private javax.swing.JButton btn_chequesDevolvidos;
    private javax.swing.JButton btn_chequesEmMaos;
    private javax.swing.JButton btn_chequesRepassados;
    private javax.swing.JButton btn_pesquisarCliente;
    private javax.swing.JButton btn_todosCheques;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
