//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConversaoDadosControlCheque.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=Cheque")]
        public string Conexao_Banco_Paradox {
            get {
                return ((string)(this["Conexao_Banco_Paradox"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost;user id=root;password=123;database=bd_control_cheque")]
        public string Conexao_Banco_Mysql {
            get {
                return ((string)(this["Conexao_Banco_Mysql"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Fontes\\ControlCheque\\02 - Desenvolvimento\\03 - Construcao\\Utilitarios\\Importac" +
            "aoDeDados\\Arquivos_Importacao_Campo_Obs\\dados_nao_tratados.txt")]
        public string arquivo_nao_tratado {
            get {
                return ((string)(this["arquivo_nao_tratado"]));
            }
            set {
                this["arquivo_nao_tratado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Fontes\\ControlCheque\\02 - Desenvolvimento\\03 - Construcao\\Utilitarios\\Importac" +
            "aoDeDados\\Arquivos_Importacao_Campo_Obs\\dados_tratados.txt")]
        public string arquivo_tratado {
            get {
                return ((string)(this["arquivo_tratado"]));
            }
            set {
                this["arquivo_tratado"] = value;
            }
        }
    }
}
